CATEGORY_MAPPING = {
    'Edeka': {
        'Exklusiv: CoffeeB': 'Tea & Coffee',
        'Kaffee ganze Bohnen': 'Tea & Coffee',
        'Kaffee gemahlen / Instant': 'Tea & Coffee',
        'Kaffeepads': 'Tea & Coffee',
        'Kaffeekapseln': 'Tea & Coffee',
        'Cappuccino-Kakao': 'Tea & Coffee',
        'Filter': 'Tea & Coffee',
        'Milch, Sahne, -Alternativen': 'Dairy Products',
        'Tee': 'Tea & Coffee',
        'Energydrinks': 'Soft Drinks & Water',
        'Säfte': 'Soft Drinks & Water',
        'Bier': 'Beer',
        'Cola': 'Soft Drinks & Water',
        'Eistee': 'Soft Drinks & Water',
        'Instant-Getränke': 'Soft Drinks & Water',
        'Limonade': 'Soft Drinks & Water',
        'Sirup': 'Soft Drinks & Water',
        'Wasser': 'Soft Drinks & Water',
        'Margarine & Butterschmalz': 'Dairy Products',
        'Aromen-Vanille': 'Baking & Cooking',
        'Backmischungen': 'Baking & Cooking',
        'Backzutaten & Dekor': 'Baking & Cooking',
        'Geliermittel-Sahnefest': 'Baking & Cooking',
        'Kuvertüre-Glasur': 'Baking & Cooking',
        'Mehl-Backpulver-Hefe': 'Baking & Cooking',
        'Nüsse & mehr': 'Snacks & Sweets',
        'Pudding-Dessert': 'Snacks & Sweets',
        'Zucker & Zuckerersatz': 'Baking & Cooking',
        'Brot-Brötchen': 'Bakery Products & Bread',
        'Fertige Kuchen': 'Bakery Products & Bread',
        'Knäckebrot-Zwieback-Getreidewaffeln': 'Bakery Products & Bread',
        'Müsli- & Fruchtriegel': 'Cereals & Bars',
        'Müsli-Cerealien': 'Cereals & Bars',
        'Honig': 'Snacks & Sweets',
        'Konfitüre & Fruchtaufstriche': 'Snacks & Sweets',
        'Nuss- & Schokocreme': 'Snacks & Sweets',
        'Käse & -cremes': 'Dairy Products',
        'Streichcreme-Aufstrich': 'Snacks & Sweets',
        'Wurst & Schinken': 'Canned Goods',
        'Öle': 'Baking & Cooking',
        'Brühen': 'Baking & Cooking',
        'Essig': 'Baking & Cooking',
        'Feinwürzmittel': 'Baking & Cooking',
        'Gewürze-Kräuter': 'Baking & Cooking',
        'Salatkräuter': 'Baking & Cooking',
        'Salz': 'Baking & Cooking',
        'Suppeneinlagen': 'Canned Goods',
        'Würzmischungen': 'Baking & Cooking',
        'Fix-Produkte': 'Baking & Cooking',
        'Fertige Soßen': 'Baking & Cooking',
        'Fonds-Soßenbinder': 'Baking & Cooking',
        'Grillsaucen': 'Baking & Cooking',
        'Ketchup-Mayonnaise': 'Baking & Cooking',
        'Salatdressing': 'Baking & Cooking',
        'Senf-Meerrettich': 'Baking & Cooking',
        'Soßen zum Anrühren': 'Baking & Cooking',
        'Tomatensoße-Pesto': 'Baking & Cooking',
        'Würzsaucen': 'Baking & Cooking',
        'Reis': 'Pasta, Rice & Legumes',
        'Nudeln': 'Pasta, Rice & Legumes',
        'Samen-Saaten': 'Pasta, Rice & Legumes',
        'Bratlinge': 'Canned Goods',
        'Hülsenfrüchte': 'Pasta, Rice & Legumes',
        'Knödel-Kartoffelprodukte': 'Canned Goods',
        'Konserven': 'Canned Goods',
        'Fischkonserven': 'Canned Goods',
        'Fleischkonserven': 'Canned Goods',
        'Gemüsekonserven': 'Canned Goods',
        'Obstkonserven': 'Canned Goods',
        'Oliven-Peperoni': 'Canned Goods',
        'Würstchen im Glas': 'Canned Goods',
        'Wurstkonserven': 'Canned Goods',
        'Schokoriegel': 'Chocolate & Sweets',
        'Bonbons & Kaugummi': 'Chocolate & Sweets',
        'Fruchtgummi & Lakritz': 'Chocolate & Sweets',
        'Schoko- Leckereien': 'Chocolate & Sweets',
        'Tafelschokolade': 'Chocolate & Sweets',
        'Chips & Knabbereien': 'Savory Snacks',
        'Gebäck-Kekse-Waffeln': 'Bakery Products & Bread',
        'Nüsse & getrocknete Früchte': 'Snacks & Sweets',
        'Gerichte zum Anrühren': 'Canned Goods',
        'Gerichte zum Erhitzen': 'Canned Goods',
        'Suppen zum Anrühren': 'Canned Goods',
        'Suppen-Eintöpfe': 'Canned Goods',
        'Trinkmahlzeiten': 'Canned Goods',
        'Rotwein': 'Wine',
        'Weißwein': 'Wine',
        'Roséwein': 'Wine',
        'Sekt-Prosecco': 'Wine',
        'Brände': 'Spirits',
        'Brandy-Weinbrand': 'Spirits',
        'Cognac': 'Spirits',
        'Gin': 'Spirits',
        'Grappa': 'Spirits',
        'Liköre & Bitter': 'Spirits',
        'Met': 'Wine',
        'Mixgetränke in Dosen': 'Spirits',
        'Party-Schnaps': 'Spirits',
        'Portwein-Sherry-Likörwein': 'Wine',
        'Rum': 'Spirits',
        'Tequila': 'Spirits',
        'Vodka': 'Spirits',
        'Wermut': 'Spirits',
        'Whisky': 'Spirits',
        'Folgemilch': 'Baby Products',
        'Glässchen': 'Baby Products',
        'Kinder-Getränke': 'Baby Products',
        'Kinder-Gerichte': 'Baby Products',
        'Pflegen-Waschen-Reinigen': 'Cleaning & Hygiene',
        'Snacks': 'Snacks & Sweets',
        'Windeln': 'Baby Products',
        'Papierware': 'Household Supplies',
        'Binden-Slipeinlagen': 'Personal Care',
        'Blasenschwäche': 'Personal Care',
        'Kondome-Gleitgele': 'Personal Care',
        'Kontaktlinsen-Pflege': 'Personal Care',
        'Rasier & Enthaarungsartikel': 'Personal Care',
        'Reisegrößen': 'Personal Care',
        'Tampons': 'Personal Care',
        'Wundschutz': 'Personal Care',
        'Männerpflege': 'Personal Care',
        'Creme-Lotions': 'Personal Care',
        'Deodorant': 'Personal Care',
        'Duschgel/ Badezusatz': 'Personal Care',
        'Gesichtspflege': 'Personal Care',
        'Haarstyling & Schutz': 'Personal Care',
        'Hand- & Fusspflege': 'Personal Care',
        'Seife': 'Personal Care',
        'Shampoo-Spülung': 'Personal Care',
        'Sonnenschutz': 'Personal Care',
        'Zahnpflege': 'Personal Care',
        'Geschirrspülmittel': 'Cleaning & Hygiene',
        'Raumerfrischer': 'Cleaning & Hygiene',
        'Reiniger': 'Cleaning & Hygiene',
        'Textilfarbe': 'Cleaning & Hygiene',
        'Waschmittel': 'Cleaning & Hygiene',
        'Weichspüler/ Wäscheparfüm': 'Cleaning & Hygiene',
        'Katzenfutter trocken': 'Pet Products',
        'Katzenfutter nass': 'Pet Products',
        'Katzen Snacks': 'Pet Products',
        'Katzenstreu': 'Pet Products',
        'Hundefutter trocken': 'Pet Products',
        'Hundefutter nass': 'Pet Products',
        'Hunde Snacks': 'Pet Products',
        'Nagerfutter': 'Pet Products',
        'Vogelfutter': 'Pet Products',
        'Beutel-Folien': 'Household Supplies',
        'Küchenzubehör': 'Household Supplies',
        'Weitere Haushaltsartikel': 'Household Supplies',
        'Batterien': 'Household Supplies',
        'Brennstoffe/Grill': 'Household Supplies',
        'Insektenschutz': 'Household Supplies',
        'Kerzen-Teelichter-Duftkerzen': 'Household Supplies',
        'Küchenrollen': 'Household Supplies',
        'Schreibwaren': 'Household Supplies',
        'Raucherbedarf': 'Household Supplies',
        'Erkältung': 'Health & Wellness',
    },
    'Netto': {
        'Rotwein': 'Wine',
        'Weißwein': 'Wine',
        'Roséwein': 'Wine',
        'Champagner': 'Wine',
        'Gin': 'Spirits',
        'Vodka': 'Spirits',
        'Whisky': 'Spirits',
        'Rum': 'Spirits',
        'Tequila': 'Spirits',
        'Cola': 'Soft Drinks & Water',
        'Energy Drinks': 'Soft Drinks & Water',
        'Wasser & Sprudel': 'Soft Drinks & Water',
        'Säfte & Nektare': 'Soft Drinks & Water',
        'Bier': 'Beer',
        'Nudeln': 'Pasta, Rice & Legumes',
        'Hülsenfrüchte': 'Pasta, Rice & Legumes',
        'Reis': 'Pasta, Rice & Legumes',
        'Fischkonserven': 'Canned Goods',
        'Schokolade': 'Chocolate & Sweets',
        'Schokoriegel': 'Chocolate & Sweets',
        'Schoko Snacks': 'Chocolate & Sweets',
        'Pralinen & Konfekt': 'Chocolate & Sweets',
        'Cookies & Gebäck': 'Bakery Products & Bread',
        'Proteinriegel': 'Cereals & Bars',
        'Gummibärchen & Lakritz': 'Chocolate & Sweets',
        'Bonbons': 'Chocolate & Sweets',
        'Chips & Nachos': 'Savory Snacks',
        'Salzstangen & Cracker': 'Savory Snacks',
        'Kaffee': 'Tea & Coffee',
        'Tee': 'Tea & Coffee',
        'Weichspüler': 'Cleaning & Hygiene',
        'Waschmittel': 'Cleaning & Hygiene',
        'Reinigungsmittel': 'Cleaning & Hygiene',
        'Folien, Papier & Beutel': 'Household Supplies',
        'Kosmetik- & Taschentücher': 'Household Supplies',
        'Katzenfutter': 'Pet Products',
        'Hundefutter': 'Pet Products',
        'Weiteres Tierfutter': 'Pet Products',
        'Babycreme & Windeln': 'Baby Products',
        'Beikost': 'Baby Products',
        'Babynahrung': 'Baby Products',
        'Milchpumpen': 'Baby Products',
        'Lätzchen': 'Baby Products',
        'Verhütung & Gleitgels': 'Household Supplies',
        'Nahrungsergänzung': 'Supplements',
        'Vapes': 'Tobacco & Related',
        'Wärme- & Massagegeräte': 'Health & Wellness',
        'Maniküre & Pediküre': 'Health & Wellness',
        'Kosmetik- & Massageliegen': 'Health & Wellness',
        'Mund- & Zahnpflege': 'Personal Care',
        'Elektrische Zahnbürsten': 'Personal Care',
        'Haut- & Körperpflege': 'Personal Care',
        'Gesichtspflege & -Reinigung': 'Personal Care',
        'Haarpflege & Styling': 'Personal Care',
        'Kosmetik-Zubehör': 'Personal Care',
    },
    'Aldi Süd': {
        'Milchprodukte': 'Dairy Products',
        'Käse': 'Dairy Products',
        'Eier': 'Eggs',
        'Fleisch': 'Meat',
        'Wurstwaren': 'Meat',
        'Fisch & Meeresfrüchte': 'Fish & Seafood',
        'TK Obst und Gemüse': 'Frozen Foods',
        'TK Pizza': 'Frozen Foods',
        'Mehl & Zucker': 'Baking & Cooking',
        'Nudeln, Reis & HülsenFrüchte': 'Pasta, Rice & Legumes',
        'Fix- & Instantprodukte': 'Instant Foods',
        'Brot': 'Bakery Products & Bread',
        'Brötchen & Baguette': 'Bakery Products & Bread',
        'Süßgebäck': 'Bakery Products & Bread',
        'Brotaufstrich & Honig': 'Snacks & Sweets',
        'Müsli, Cornflakes, Flocken': 'Cereals & Bars',
        'Kaffee': 'Tea & Coffee',
        'Tee': 'Tea & Coffee',
        'Wasser': 'Soft Drinks & Water',
        'Saft & Nektar': 'Soft Drinks & Water',
        'Cola, Limonaden, Eistee': 'Soft Drinks & Water',
        'Energy Drinks': 'Soft Drinks & Water',
        'Rotwein': 'Wine',
        'Roséwein': 'Wine',
        'Weißwein': 'Wine',
        'Spirituosen': 'Spirits',
        'Schaum-/Perlwein': 'Wine',
        'Bier': 'Beer',
        'Nüsse & Trockenfrüchte': 'Snacks & Sweets',
        'Bonbons': 'Chocolate & Sweets',
        'Kekse': 'Bakery Products & Bread',
        'Schokolade': 'Chocolate & Sweets',
        'Riegel': 'Chocolate & Sweets',
        'Salziges': 'Savory Snacks',
        'Haarpflege': 'Personal Care',
        'Körperpflege': 'Personal Care',
        'Mund- & Zahnpflege': 'Personal Care',
        'Make-Up': 'Personal Care',
        'Babynahrung': 'Baby Products',
        'Babypflege': 'Baby Products',
        'Windeln': 'Baby Products',
        'Waschmittel': 'Cleaning & Hygiene',
        'Tierbedarf': 'Pet Products',
        'ALDI Guthaben- & Geschenkkarten': 'Gift Cards',
        'Eis': 'Frozen Foods',
        'Vegetarisches und veganes Grillgut': 'Vegetarian & Vegan',
        'Haushalt': 'Household Supplies'
    },
    'Kaufland': {
        'Gebäck & Knabbereien': 'Snacks & Sweets',
        'Schokoladen': 'Chocolate & Sweets',
        'Süße Adventskalender': 'Chocolate & Sweets',
        'Kaugummis': 'Chocolate & Sweets',
        'Fruchtgummis': 'Chocolate & Sweets',
        'Sonstige Süßigkeiten': 'Chocolate & Sweets',
        'Bonbons': 'Chocolate & Sweets',
        'Kekse': 'Bakery Products & Bread',
        'Pralinen': 'Chocolate & Sweets',
        'Müsliriegel': 'Cereals & Bars',
        'Schokoriegel': 'Chocolate & Sweets',
        'Popcorn': 'Savory Snacks',
        'Lakritze': 'Chocolate & Sweets',
        'Lutscher': 'Chocolate & Sweets',
        'Oster-Süßigkeiten': 'Chocolate & Sweets',
        'Mäusespeck': 'Chocolate & Sweets',
        'Kaubonbons': 'Chocolate & Sweets',
        'Alkoholhaltige Süßigkeiten': 'Chocolate & Sweets',
        'Weihnachtssüßwaren': 'Chocolate & Sweets',
        'Zuckerstangen': 'Chocolate & Sweets',
        'Trüffel': 'Chocolate & Sweets',
        'Kaffeekapseln': 'Tea & Coffee',
        'Kaffeebohnen': 'Tea & Coffee',
        'Instant Kaffees': 'Tea & Coffee',
        'Kaffeepads': 'Tea & Coffee',
        'Tees': 'Tea & Coffee',
        'Lose Tees': 'Tea & Coffee',
        'Spirituosen': 'Spirits',
        'Rotwein': 'Wine',
        'Glühwein': 'Wine',
        'Weißwein': 'Wine',
        'Roséwein': 'Wine',
        'Süßwein': 'Wine',
        'Fruchtwein': 'Wine',
        'Met': 'Wine',
        'Mineralwasser': 'Soft Drinks & Water',
        'Sirups': 'Soft Drinks & Water',
        'Softdrinks': 'Soft Drinks & Water',
        'Fruchtsäfte': 'Juices',
        'Instant Getränkepulver': 'Soft Drinks & Water',
        'Sonstige alkoholfreie Getränke': 'Soft Drinks & Water',
        'Energy-Drinks': 'Soft Drinks & Water',
        'Eistees': 'Soft Drinks & Water',
        'Fruchtschorlen': 'Soft Drinks & Water',
        'Nektare': 'Juices',
        'Kakaos': 'Chocolate & Sweets',
        'Kakaopulver': 'Chocolate & Sweets',
        'Trinkschokoladen': 'Chocolate & Sweets',
        'Kakaopads & Kakaokapseln': 'Chocolate & Sweets',
        'Desserts': 'Snacks & Sweets',
        'Puddings': 'Dairy Products',
        'Backzutaten': 'Baking & Cooking',
        'Brotaufstriche': 'Snacks & Sweets',
        'Öle & Essige': 'Baking & Cooking',
        'Gewürze & Saucen': 'Baking & Cooking',
        'Fleisch-, Würstchen- und Fischkonserven': 'Canned Goods',
        'Obst- und Gemüsekonserven': 'Canned Goods',
        'Sonstige Backwaren': 'Bakery Products & Bread',
        'Brote': 'Bakery Products & Bread',
        'Waffeln': 'Bakery Products & Bread',
        'Knäckebrot': 'Bakery Products & Bread',
        'Brötchen': 'Bakery Products & Bread',
        'Muffins': 'Bakery Products & Bread',
        'Kuchen': 'Bakery Products & Bread',
        'Torten': 'Bakery Products & Bread',
        'Milch': 'Dairy Products',
        'Pflanzendrinks': 'Dairy Products',
        'Sonstige Käse- & Milchprodukte': 'Dairy Products',
        'Käse': 'Dairy Products',
        'Butter': 'Dairy Products',
        'Quark': 'Dairy Products',
        'Joghurts': 'Dairy Products',
        'Wurst': 'Meat',
        'Fleisch': 'Meat',
        'Meeresfrüchte': 'Fish & Seafood',
        'Fische': 'Fish & Seafood',
        'Müslis': 'Cereals & Bars',
        'Trockenfrüchte': 'Snacks & Sweets',
        'Getreide': 'Cereals & Bars',
        'Cornflakes': 'Cereals & Bars',
        'Fertiggerichte': 'Instant Foods',
        'Nudeln': 'Pasta, Rice & Legumes',
        'Reis': 'Pasta, Rice & Legumes',
        'Hülsenfrüchte': 'Pasta, Rice & Legumes',
        'Nahrungsergänzungsmittel': 'Health & Wellness',
    }
}
